// English UI chrome copy, centralized so localization later is a matter of
// adding a second module and a switch -- see docs/ARCHITECTURE.md "Frontend".
// Creator-facing generated content is rendered verbatim in whatever language
// it was generated in and does NOT go through this file.
export const strings = {
  nav: {
    inspiration: "Inspiration",
    ideas: "Ideas",
    todo: "Todo",
  },
  common: {
    loading: "Loading…",
    error: "Something went wrong",
    retry: "Retry",
    back: "Back",
    loadMore: "Load more",
    save: "Save",
    cancel: "Cancel",
    analyzing: "Analyzing…",
  },
  dashboard: {
    generateIdeas: "Generate ideas",
  },
  inspiration: {
    title: "Inspiration",
    subtitle: "TikToks you saved to Notion for inspiration.",
    empty: "No inspiration items yet. Save TikTok links to your Notion database, then sync.",
    sync: "Sync Notion",
    syncing: "Syncing…",
    reanalyze: "Analyze",
    reanalyzeAgain: "Re-analyze",
    detailTitle: "Inspiration detail",
    markUsed: "Mark as used",
    unmarkUsed: "Unmark as used",
    usedBadge: "Used",
    usedHint: "Won't be used as context for new ideas.",
    availability: {
      full_media: "Full video available",
      transcript_only: "Transcript only",
      metadata_only: "Metadata only",
      unavailable: "Unavailable",
    },
  },
  ideas: {
    title: "Ideas",
    subtitle: "AI-generated ideas based on your saved inspiration.",
    empty: "No ideas yet. Generate some from your saved inspiration below.",
    generate: "Generate ideas",
    generating: "Generating…",
    count: "How many ideas",
    instructions: "Anything specific in mind? (optional)",
    outputLanguage: "Language",
    detailTitle: "Idea detail",
    feedback: "Feedback",
    feedbackComment: "Comment (optional)",
    submitFeedback: "Submit feedback",
    generateBrief: "Generate brief",
    generatingBrief: "Generating brief…",
    generateScript: "Generate script",
    generatingScript: "Generating script…",
    scriptMode: "Script mode",
    brief: "Production brief",
    script: "Script",
    hookOptions: "Hook options",
    outline: "Outline",
    sourceMedia: "Source images",
    sourcingMedia: "Sourcing…",
    regenerateMedia: "Get new images",
    images: "Images",
    memes: "Memes",
    addToTodo: "Add to Todo",
    addingToTodo: "Adding…",
    inTodo: "In Todo",
    novelty: {
      aligned: "Aligned",
      stretch: "Stretch",
      experimental: "Experimental",
    },
    similarity: {
      new: "New territory",
      related_but_distinct: "Related but distinct",
      follow_up: "Follow-up",
      too_similar: "Too similar to an existing post",
    },
    status: {
      proposed: "Proposed",
      saved: "In Todo",
      done: "Done",
      archived: "Archived",
    },
  },
  todo: {
    title: "Todo",
    subtitle: "Ideas you're planning to film. Finalize the brief/script, then mark done.",
    empty: "Nothing here yet. Add an idea to Todo from the Ideas page.",
    markDone: "Mark done",
    markingDone: "Marking done…",
    doneHint: "Marks the idea done and the inspiration it came from as already used.",
  },
};
