// English UI chrome copy for the MVP, centralized so localization later is a
// matter of adding a second module and a switch -- see docs/ARCHITECTURE.md
// "Frontend". Creator-facing generated content is rendered verbatim in
// whatever language it was generated in and does NOT go through this file.
export const strings = {
  nav: {
    dashboard: "Dashboard",
    posts: "My Posts",
    inspiration: "Inspiration",
    profile: "Profile",
    ideas: "Ideas",
  },
  common: {
    loading: "Loading…",
    error: "Something went wrong",
    retry: "Retry",
    back: "Back",
    loadMore: "Load more",
    createdAt: "Added",
    save: "Save",
    cancel: "Cancel",
  },
  dashboard: {
    title: "Dashboard",
    subtitle: "Your personal TikTok content planning workspace.",
    syncTikTok: "Sync TikTok posts",
    syncNotion: "Sync Notion inspiration",
    syncing: "Syncing…",
    postsCard: "Own posts analyzed",
    inspirationCard: "Inspiration items",
    ideasCard: "Ideas generated",
    profileCard: "Content profile",
    noProfileYet: "No profile built yet",
    goToProfile: "View profile",
    goToPosts: "View posts",
    goToInspiration: "View inspiration",
    goToIdeas: "View ideas",
    quickActions: "Quick actions",
    generateIdeas: "Generate new ideas",
  },
  posts: {
    title: "My Posts",
    subtitle: "Posts synced from your TikTok account.",
    empty: "No posts yet. Sync your TikTok account to pull in your published videos.",
    sync: "Sync TikTok posts",
    reanalyze: "Analyze",
    reanalyzing: "Analyzing…",
    reanalyzeAgain: "Re-analyze",
    status: {
      pending: "Not analyzed yet",
      processing: "Analyzing…",
      completed: "Analyzed",
      failed: "Analysis failed",
    },
    detailTitle: "Post detail",
    analysis: "Content analysis",
    noAnalysis: "This post hasn't been analyzed yet.",
  },
  inspiration: {
    title: "Inspiration",
    subtitle: "TikToks you saved to Notion for inspiration.",
    empty: "No inspiration items yet. Save TikTok links to your Notion database, then sync.",
    sync: "Sync Notion",
    syncing: "Syncing…",
    reanalyze: "Analyze",
    reanalyzeAgain: "Re-analyze",
    detailTitle: "Inspiration detail",
    availability: {
      full_media: "Full video available",
      transcript_only: "Transcript only",
      metadata_only: "Metadata only",
      unavailable: "Unavailable",
    },
  },
  profile: {
    title: "Content Profile",
    subtitle: "A derived snapshot of your recurring topics, formats, and hooks.",
    empty: "No content profile has been built yet.",
    emptyHint: "Analyze some posts first, then build your profile.",
    build: "Build profile",
    rebuild: "Rebuild profile",
    building: "Building…",
    sampleSize: "Based on",
    pillars: "Content pillars",
    formats: "Format distribution",
    underused: "Underused formats",
    hooks: "Typical hooks",
    structures: "Typical structures",
    tone: "Tone distribution",
    gaps: "Content gaps",
    observations: "Observations",
    confidence: "Overall confidence",
  },
  ideas: {
    title: "Ideas",
    subtitle: "AI-generated ideas grounded in your content and inspiration.",
    empty: "No ideas generated yet.",
    generate: "Generate ideas",
    generating: "Generating…",
    count: "How many ideas",
    contentPillar: "Content pillar (optional)",
    format: "Recommended format (optional)",
    instructions: "Extra instructions (optional)",
    excludedSubjects: "Subjects to avoid (comma-separated, optional)",
    outputLanguage: "Output language",
    detailTitle: "Idea detail",
    feedback: "Feedback",
    feedbackComment: "Comment (optional)",
    submitFeedback: "Submit feedback",
    generateBrief: "Generate brief",
    generatingBrief: "Generating brief…",
    generateScript: "Generate script",
    generatingScript: "Generating script…",
    scriptMode: "Script mode",
    brief: "Production brief",
    script: "Script",
    hookOptions: "Hook options",
    outline: "Outline",
    novelty: {
      aligned: "Aligned",
      stretch: "Stretch",
      experimental: "Experimental",
    },
    similarity: {
      new: "New territory",
      related_but_distinct: "Related but distinct",
      follow_up: "Follow-up",
      too_similar: "Too similar to an existing post",
    },
  },
};
